# Generated by Django 5.0.8 on 2024-08-25 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_pseudonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.literaryformat'),
        ),
    ]
