# Generated by Django 5.0.8 on 2024-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='labels'),
        ),
    ]
